name: getx_chat
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.1.0
  chewie: ^1.2.2
  cloud_firestore: ^2.0.0
  cupertino_icons: ^1.0.2
  emoji_picker_flutter: ^1.0.6
  firebase_auth: ^1.1.2
  firebase_core: ^1.1.0
  firebase_storage: ^10.0.1
  flutter_image_compress: ^1.0.0
  flutter_slidable: ^0.6.0
  get: ^4.2.4
  image_picker: ^0.8.2
  internet_connection_checker: ^0.0.1+2
  multi_image_picker: ^4.8.1
  uuid: ^3.0.4
  video_compress: ^3.1.0
  video_player: ^2.1.12
  video_thumbnail: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
